name: Sync Browserless and Redis to My ACR

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Alibaba Cloud Personal ACR
        uses: docker/login-action@v2.2.0
        with:
          registry: crpi-7p9pej2rxzfmniwc.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sync Required Images
        run: |
          # 1. 同步 browserless/chrome (保留这个，方便以后更新)
          echo "Syncing browserless/chrome..."
          skopeo copy \
            docker://docker.io/browserless/chrome:latest \
            docker://crpi-7p9pej2rxzfmniwc.cn-hangzhou.personal.cr.aliyuncs.com/micochen/browserless-chrome:latest

          # 2. 新增！同步 Redis
          echo "Syncing redis..."
          skopeo copy \
            docker://docker.io/library/redis:alpine \
            docker://crpi-7p9pej2rxzfmniwc.cn-hangzhou.personal.cr.aliyuncs.com/micochen/redis:alpine